/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: robotic_arm

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container2 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 640);
    lv_obj_set_height(ui_Container2, 480);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, -60);
    lv_obj_set_align(ui_Container2, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_uvcframe = lv_img_create(ui_Container2);
    lv_obj_set_width(ui_uvcframe, LV_SIZE_CONTENT);   /// 640
    lv_obj_set_height(ui_uvcframe, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_uvcframe, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uvcframe, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_uvcframe, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RegfButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_RegfButton, 220);
    lv_obj_set_height(ui_RegfButton, 65);
    lv_obj_set_x(ui_RegfButton, 320);
    lv_obj_set_y(ui_RegfButton, -220);
    lv_obj_set_align(ui_RegfButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RegfButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RegfButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_RegfButton);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Recognize");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogTextArea = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_LogTextArea, 640);
    lv_obj_set_height(ui_LogTextArea, 100);
    lv_obj_set_x(ui_LogTextArea, -190);
    lv_obj_set_y(ui_LogTextArea, 243);
    lv_obj_set_align(ui_LogTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_LogTextArea, "Placeholder...");

    ui_ClearButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ClearButton, 220);
    lv_obj_set_height(ui_ClearButton, 65);
    lv_obj_set_x(ui_ClearButton, 320);
    lv_obj_set_y(ui_ClearButton, -100);
    lv_obj_set_align(ui_ClearButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ClearButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ClearButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_ClearButton);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Clear");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

}
