// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Panthera_Joint_Ctrl

#include "../ui.h"

lv_obj_t * ui_RobotCtrlScreen = NULL;
lv_obj_t * ui_EnableSwitch = NULL;
lv_obj_t * ui_EnableLabel = NULL;
lv_obj_t * ui_SetZeroButton = NULL;
lv_obj_t * ui_SetZeroLabel = NULL;
lv_obj_t * ui_J1Label = NULL;
lv_obj_t * ui_J2Label = NULL;
lv_obj_t * ui_J3Label = NULL;
lv_obj_t * ui_J4Label = NULL;
lv_obj_t * ui_J5Label = NULL;
lv_obj_t * ui_J6Label = NULL;
lv_obj_t * ui_G1Label = NULL;
lv_obj_t * ui_GoZeroButton = NULL;
lv_obj_t * ui_GoZeroLabel = NULL;
lv_obj_t * ui_J1AngleLabel = NULL;
lv_obj_t * ui_J1LeftImage = NULL;
lv_obj_t * ui_J1RightImage = NULL;
lv_obj_t * ui_J3LeftImage = NULL;
lv_obj_t * ui_J4LeftImage = NULL;
lv_obj_t * ui_J2LeftImage = NULL;
lv_obj_t * ui_J5LeftImage = NULL;
lv_obj_t * ui_J6LeftImage = NULL;
lv_obj_t * ui_G1LeftImage = NULL;
lv_obj_t * ui_J2RightImage = NULL;
lv_obj_t * ui_J3RightImage = NULL;
lv_obj_t * ui_J4RightImage = NULL;
lv_obj_t * ui_J5RightImage = NULL;
lv_obj_t * ui_J6RightImage = NULL;
lv_obj_t * ui_G1RightImage = NULL;
lv_obj_t * ui_J2AngleLabel = NULL;
lv_obj_t * ui_J3AngleLabel = NULL;
lv_obj_t * ui_J4AngleLabel = NULL;
lv_obj_t * ui_J5AngleLabel = NULL;
lv_obj_t * ui_J6AngleLabel = NULL;
lv_obj_t * ui_G1AngleLabel = NULL;
// event functions

// build functions

void ui_RobotCtrlScreen_screen_init(void)
{
    ui_RobotCtrlScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_RobotCtrlScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EnableSwitch = lv_switch_create(ui_RobotCtrlScreen);
    lv_obj_set_width(ui_EnableSwitch, 167);
    lv_obj_set_height(ui_EnableSwitch, 70);
    lv_obj_set_x(ui_EnableSwitch, 40);
    lv_obj_set_y(ui_EnableSwitch, -230);
    lv_obj_set_align(ui_EnableSwitch, LV_ALIGN_CENTER);
    lv_obj_set_style_border_width(ui_EnableSwitch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EnableLabel = lv_label_create(ui_EnableSwitch);
    lv_obj_set_width(ui_EnableLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EnableLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_EnableLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EnableLabel, "EN");
    lv_obj_set_style_text_font(ui_EnableLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetZeroButton = lv_button_create(ui_RobotCtrlScreen);
    lv_obj_set_width(ui_SetZeroButton, 150);
    lv_obj_set_height(ui_SetZeroButton, 70);
    lv_obj_set_x(ui_SetZeroButton, 233);
    lv_obj_set_y(ui_SetZeroButton, -230);
    lv_obj_set_align(ui_SetZeroButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetZeroButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SetZeroButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SetZeroLabel = lv_label_create(ui_SetZeroButton);
    lv_obj_set_width(ui_SetZeroLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetZeroLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SetZeroLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetZeroLabel, "Set Zero");
    lv_obj_set_style_text_font(ui_SetZeroLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_J1Label = lv_label_create(ui_RobotCtrlScreen);
    lv_obj_set_width(ui_J1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J1Label, 40);
    lv_obj_set_y(ui_J1Label, -160);
    lv_obj_set_align(ui_J1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_J1Label, "J1:");
    lv_obj_set_style_text_font(ui_J1Label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_J2Label = lv_label_create(ui_RobotCtrlScreen);
    lv_obj_set_width(ui_J2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J2Label, 40);
    lv_obj_set_y(ui_J2Label, -100);
    lv_obj_set_align(ui_J2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_J2Label, "J2:");
    lv_obj_set_style_text_font(ui_J2Label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_J3Label = lv_label_create(ui_RobotCtrlScreen);
    lv_obj_set_width(ui_J3Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J3Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J3Label, 40);
    lv_obj_set_y(ui_J3Label, -40);
    lv_obj_set_align(ui_J3Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_J3Label, "J3:");
    lv_obj_set_style_text_font(ui_J3Label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_J4Label = lv_label_create(ui_RobotCtrlScreen);
    lv_obj_set_width(ui_J4Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J4Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J4Label, 40);
    lv_obj_set_y(ui_J4Label, 20);
    lv_obj_set_align(ui_J4Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_J4Label, "J4:");
    lv_obj_set_style_text_font(ui_J4Label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_J5Label = lv_label_create(ui_RobotCtrlScreen);
    lv_obj_set_width(ui_J5Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J5Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J5Label, 40);
    lv_obj_set_y(ui_J5Label, 80);
    lv_obj_set_align(ui_J5Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_J5Label, "J5:");
    lv_obj_set_style_text_font(ui_J5Label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_J6Label = lv_label_create(ui_RobotCtrlScreen);
    lv_obj_set_width(ui_J6Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J6Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J6Label, 40);
    lv_obj_set_y(ui_J6Label, 140);
    lv_obj_set_align(ui_J6Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_J6Label, "J6:");
    lv_obj_set_style_text_font(ui_J6Label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_G1Label = lv_label_create(ui_RobotCtrlScreen);
    lv_obj_set_width(ui_G1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_G1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_G1Label, 40);
    lv_obj_set_y(ui_G1Label, 200);
    lv_obj_set_align(ui_G1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_G1Label, "G1:");
    lv_obj_set_style_text_font(ui_G1Label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GoZeroButton = lv_button_create(ui_RobotCtrlScreen);
    lv_obj_set_width(ui_GoZeroButton, 150);
    lv_obj_set_height(ui_GoZeroButton, 70);
    lv_obj_set_x(ui_GoZeroButton, 423);
    lv_obj_set_y(ui_GoZeroButton, -230);
    lv_obj_set_align(ui_GoZeroButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GoZeroButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_GoZeroButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GoZeroLabel = lv_label_create(ui_GoZeroButton);
    lv_obj_set_width(ui_GoZeroLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GoZeroLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GoZeroLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GoZeroLabel, "Go Zero");
    lv_obj_set_style_text_font(ui_GoZeroLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_J1AngleLabel = lv_label_create(ui_RobotCtrlScreen);
    lv_obj_set_width(ui_J1AngleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J1AngleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J1AngleLabel, 280);
    lv_obj_set_y(ui_J1AngleLabel, -160);
    lv_obj_set_align(ui_J1AngleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_J1AngleLabel, "0");
    lv_obj_set_style_text_font(ui_J1AngleLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_J1LeftImage = lv_image_create(ui_RobotCtrlScreen);
    lv_image_set_src(ui_J1LeftImage, &ui_img_left_png);
    lv_obj_set_width(ui_J1LeftImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J1LeftImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J1LeftImage, 160);
    lv_obj_set_y(ui_J1LeftImage, -160);
    lv_obj_set_align(ui_J1LeftImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_J1LeftImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_J1LeftImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_J1RightImage = lv_image_create(ui_RobotCtrlScreen);
    lv_image_set_src(ui_J1RightImage, &ui_img_right_png);
    lv_obj_set_width(ui_J1RightImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J1RightImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J1RightImage, 400);
    lv_obj_set_y(ui_J1RightImage, -160);
    lv_obj_set_align(ui_J1RightImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_J1RightImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_J1RightImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_J3LeftImage = lv_image_create(ui_RobotCtrlScreen);
    lv_image_set_src(ui_J3LeftImage, &ui_img_left_png);
    lv_obj_set_width(ui_J3LeftImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J3LeftImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J3LeftImage, 160);
    lv_obj_set_y(ui_J3LeftImage, -40);
    lv_obj_set_align(ui_J3LeftImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_J3LeftImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_J3LeftImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_J4LeftImage = lv_image_create(ui_RobotCtrlScreen);
    lv_image_set_src(ui_J4LeftImage, &ui_img_left_png);
    lv_obj_set_width(ui_J4LeftImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J4LeftImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J4LeftImage, 160);
    lv_obj_set_y(ui_J4LeftImage, 20);
    lv_obj_set_align(ui_J4LeftImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_J4LeftImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_J4LeftImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_J2LeftImage = lv_image_create(ui_RobotCtrlScreen);
    lv_image_set_src(ui_J2LeftImage, &ui_img_left_png);
    lv_obj_set_width(ui_J2LeftImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J2LeftImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J2LeftImage, 160);
    lv_obj_set_y(ui_J2LeftImage, -100);
    lv_obj_set_align(ui_J2LeftImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_J2LeftImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_J2LeftImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_J5LeftImage = lv_image_create(ui_RobotCtrlScreen);
    lv_image_set_src(ui_J5LeftImage, &ui_img_left_png);
    lv_obj_set_width(ui_J5LeftImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J5LeftImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J5LeftImage, 160);
    lv_obj_set_y(ui_J5LeftImage, 80);
    lv_obj_set_align(ui_J5LeftImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_J5LeftImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_J5LeftImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_J6LeftImage = lv_image_create(ui_RobotCtrlScreen);
    lv_image_set_src(ui_J6LeftImage, &ui_img_left_png);
    lv_obj_set_width(ui_J6LeftImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J6LeftImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J6LeftImage, 160);
    lv_obj_set_y(ui_J6LeftImage, 140);
    lv_obj_set_align(ui_J6LeftImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_J6LeftImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_J6LeftImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_G1LeftImage = lv_image_create(ui_RobotCtrlScreen);
    lv_image_set_src(ui_G1LeftImage, &ui_img_left_png);
    lv_obj_set_width(ui_G1LeftImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_G1LeftImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_G1LeftImage, 160);
    lv_obj_set_y(ui_G1LeftImage, 200);
    lv_obj_set_align(ui_G1LeftImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_G1LeftImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_G1LeftImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_J2RightImage = lv_image_create(ui_RobotCtrlScreen);
    lv_image_set_src(ui_J2RightImage, &ui_img_right_png);
    lv_obj_set_width(ui_J2RightImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J2RightImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J2RightImage, 400);
    lv_obj_set_y(ui_J2RightImage, -100);
    lv_obj_set_align(ui_J2RightImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_J2RightImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_J2RightImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_J3RightImage = lv_image_create(ui_RobotCtrlScreen);
    lv_image_set_src(ui_J3RightImage, &ui_img_right_png);
    lv_obj_set_width(ui_J3RightImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J3RightImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J3RightImage, 400);
    lv_obj_set_y(ui_J3RightImage, -40);
    lv_obj_set_align(ui_J3RightImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_J3RightImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_J3RightImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_J4RightImage = lv_image_create(ui_RobotCtrlScreen);
    lv_image_set_src(ui_J4RightImage, &ui_img_right_png);
    lv_obj_set_width(ui_J4RightImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J4RightImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J4RightImage, 400);
    lv_obj_set_y(ui_J4RightImage, 20);
    lv_obj_set_align(ui_J4RightImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_J4RightImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_J4RightImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_J5RightImage = lv_image_create(ui_RobotCtrlScreen);
    lv_image_set_src(ui_J5RightImage, &ui_img_right_png);
    lv_obj_set_width(ui_J5RightImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J5RightImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J5RightImage, 400);
    lv_obj_set_y(ui_J5RightImage, 80);
    lv_obj_set_align(ui_J5RightImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_J5RightImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_J5RightImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_J6RightImage = lv_image_create(ui_RobotCtrlScreen);
    lv_image_set_src(ui_J6RightImage, &ui_img_right_png);
    lv_obj_set_width(ui_J6RightImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J6RightImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J6RightImage, 400);
    lv_obj_set_y(ui_J6RightImage, 140);
    lv_obj_set_align(ui_J6RightImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_J6RightImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_J6RightImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_G1RightImage = lv_image_create(ui_RobotCtrlScreen);
    lv_image_set_src(ui_G1RightImage, &ui_img_right_png);
    lv_obj_set_width(ui_G1RightImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_G1RightImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_G1RightImage, 400);
    lv_obj_set_y(ui_G1RightImage, 200);
    lv_obj_set_align(ui_G1RightImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_G1RightImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_G1RightImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_J2AngleLabel = lv_label_create(ui_RobotCtrlScreen);
    lv_obj_set_width(ui_J2AngleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J2AngleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J2AngleLabel, 280);
    lv_obj_set_y(ui_J2AngleLabel, -100);
    lv_obj_set_align(ui_J2AngleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_J2AngleLabel, "0");
    lv_obj_set_style_text_font(ui_J2AngleLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_J3AngleLabel = lv_label_create(ui_RobotCtrlScreen);
    lv_obj_set_width(ui_J3AngleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J3AngleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J3AngleLabel, 280);
    lv_obj_set_y(ui_J3AngleLabel, -40);
    lv_obj_set_align(ui_J3AngleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_J3AngleLabel, "0");
    lv_obj_set_style_text_font(ui_J3AngleLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_J4AngleLabel = lv_label_create(ui_RobotCtrlScreen);
    lv_obj_set_width(ui_J4AngleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J4AngleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J4AngleLabel, 280);
    lv_obj_set_y(ui_J4AngleLabel, 20);
    lv_obj_set_align(ui_J4AngleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_J4AngleLabel, "0");
    lv_obj_set_style_text_font(ui_J4AngleLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_J5AngleLabel = lv_label_create(ui_RobotCtrlScreen);
    lv_obj_set_width(ui_J5AngleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J5AngleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J5AngleLabel, 280);
    lv_obj_set_y(ui_J5AngleLabel, 80);
    lv_obj_set_align(ui_J5AngleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_J5AngleLabel, "0");
    lv_obj_set_style_text_font(ui_J5AngleLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_J6AngleLabel = lv_label_create(ui_RobotCtrlScreen);
    lv_obj_set_width(ui_J6AngleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_J6AngleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_J6AngleLabel, 280);
    lv_obj_set_y(ui_J6AngleLabel, 140);
    lv_obj_set_align(ui_J6AngleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_J6AngleLabel, "0");
    lv_obj_set_style_text_font(ui_J6AngleLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_G1AngleLabel = lv_label_create(ui_RobotCtrlScreen);
    lv_obj_set_width(ui_G1AngleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_G1AngleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_G1AngleLabel, 280);
    lv_obj_set_y(ui_G1AngleLabel, 200);
    lv_obj_set_align(ui_G1AngleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_G1AngleLabel, "0");
    lv_obj_set_style_text_font(ui_G1AngleLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_RobotCtrlScreen_screen_destroy(void)
{
    if(ui_RobotCtrlScreen) lv_obj_del(ui_RobotCtrlScreen);

    // NULL screen variables
    ui_RobotCtrlScreen = NULL;
    ui_EnableSwitch = NULL;
    ui_EnableLabel = NULL;
    ui_SetZeroButton = NULL;
    ui_SetZeroLabel = NULL;
    ui_J1Label = NULL;
    ui_J2Label = NULL;
    ui_J3Label = NULL;
    ui_J4Label = NULL;
    ui_J5Label = NULL;
    ui_J6Label = NULL;
    ui_G1Label = NULL;
    ui_GoZeroButton = NULL;
    ui_GoZeroLabel = NULL;
    ui_J1AngleLabel = NULL;
    ui_J1LeftImage = NULL;
    ui_J1RightImage = NULL;
    ui_J3LeftImage = NULL;
    ui_J4LeftImage = NULL;
    ui_J2LeftImage = NULL;
    ui_J5LeftImage = NULL;
    ui_J6LeftImage = NULL;
    ui_G1LeftImage = NULL;
    ui_J2RightImage = NULL;
    ui_J3RightImage = NULL;
    ui_J4RightImage = NULL;
    ui_J5RightImage = NULL;
    ui_J6RightImage = NULL;
    ui_G1RightImage = NULL;
    ui_J2AngleLabel = NULL;
    ui_J3AngleLabel = NULL;
    ui_J4AngleLabel = NULL;
    ui_J5AngleLabel = NULL;
    ui_J6AngleLabel = NULL;
    ui_G1AngleLabel = NULL;

}
