// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Panthera_Joint_Ctrl

#ifndef UI_ROBOTCTRLSCREEN_H
#define UI_ROBOTCTRLSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RobotCtrlScreen
extern void ui_RobotCtrlScreen_screen_init(void);
extern void ui_RobotCtrlScreen_screen_destroy(void);
extern lv_obj_t * ui_RobotCtrlScreen;
extern lv_obj_t * ui_EnableSwitch;
extern lv_obj_t * ui_EnableLabel;
extern lv_obj_t * ui_SetZeroButton;
extern lv_obj_t * ui_SetZeroLabel;
extern lv_obj_t * ui_J1Label;
extern lv_obj_t * ui_J2Label;
extern lv_obj_t * ui_J3Label;
extern lv_obj_t * ui_J4Label;
extern lv_obj_t * ui_J5Label;
extern lv_obj_t * ui_J6Label;
extern lv_obj_t * ui_G1Label;
extern lv_obj_t * ui_GoZeroButton;
extern lv_obj_t * ui_GoZeroLabel;
extern lv_obj_t * ui_J1AngleLabel;
extern lv_obj_t * ui_J1LeftImage;
extern lv_obj_t * ui_J1RightImage;
extern lv_obj_t * ui_J3LeftImage;
extern lv_obj_t * ui_J4LeftImage;
extern lv_obj_t * ui_J2LeftImage;
extern lv_obj_t * ui_J5LeftImage;
extern lv_obj_t * ui_J6LeftImage;
extern lv_obj_t * ui_G1LeftImage;
extern lv_obj_t * ui_J2RightImage;
extern lv_obj_t * ui_J3RightImage;
extern lv_obj_t * ui_J4RightImage;
extern lv_obj_t * ui_J5RightImage;
extern lv_obj_t * ui_J6RightImage;
extern lv_obj_t * ui_G1RightImage;
extern lv_obj_t * ui_J2AngleLabel;
extern lv_obj_t * ui_J3AngleLabel;
extern lv_obj_t * ui_J4AngleLabel;
extern lv_obj_t * ui_J5AngleLabel;
extern lv_obj_t * ui_J6AngleLabel;
extern lv_obj_t * ui_G1AngleLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
