// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Panthera_Joint_Ctrl

#ifndef _PANTHERA_JOINT_CTRL_UI_H
#define _PANTHERA_JOINT_CTRL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_RobotCtrlScreen.h"

///////////////////// VARIABLES ////////////////////


// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_left_png);    // assets/left.png
LV_IMG_DECLARE(ui_img_right_png);    // assets/right.png

// UI INIT
void ui_panthera_ctrl_init(void);
void ui_panthera_ctrl_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
